// 공식 출처와 일정 정밀도를 함께 보존하는 초기 시험 카탈로그를 제공한다.
import type { Exam, PreparationItem } from "./model";

const HISTORY_URL = "https://www.historyexam.go.kr/pageLink.do?link=examSchedule";
const HISTORY_GUIDE_URL = "https://www.historyexam.go.kr/pageLink.do?link=apyexmInfo";
const QNET_URL = "https://www.q-net.or.kr/man001.do?gId=HTML5&gSite=Q";
const KORCHAM_URL = "https://license.korcham.net/";
const CIVIL_URL = "https://gongmuwon.gosi.kr/";

const genericPreparation = (source: string): PreparationItem[] => [
  {
    id: "identity-check",
    category: "identity",
    label: "공식 신분증 기준 확인",
    detail: "시험마다 인정 신분증이 다를 수 있어 최신 응시요강을 확인하세요.",
    required: true,
    officialSourceUrl: source,
  },
];

export const exams: Exam[] = [
  {
    id: "history-advanced",
    slug: "history-advanced",
    name: "한국사능력검정시험 심화",
    shortName: "한능검 심화",
    organizer: "국사편찬위원회",
    category: "한국사·공공",
    goals: ["취업", "공무원", "자기계발"],
    description: "공공기관·채용·진학 활용 범위가 넓은 한국사 인증시험입니다.",
    officialUrl: HISTORY_URL,
    applicationUrl: "https://www.historyexam.go.kr/",
    scheduleType: "round",
    trustLevel: "official-notice",
    lastVerifiedAt: "2026-07-16T00:00:00+09:00",
    timePrecision: "exact",
    practical: false,
    eligibilityRestricted: false,
    duration: "short",
    feeLabel: "심화 27,000원",
    caution: "회차별 시행 등급과 지역별 정기접수 시간을 공식 공고에서 확인하세요.",
    events: [
      {
        id: "history-79-cancel-seat",
        examId: "history-advanced",
        type: "application-open",
        title: "제79회 취소좌석 접수",
        startAt: "2026-07-21T10:00:00+09:00",
        endAt: "2026-07-24T17:00:00+09:00",
        timePrecision: "exact",
        officialSourceUrl: HISTORY_URL,
        confirmed: true,
        regionCode: "ALL",
      },
      {
        id: "history-79-ticket",
        examId: "history-advanced",
        type: "ticket",
        title: "제79회 수험표 출력",
        startAt: "2026-08-04T10:00:00+09:00",
        timePrecision: "exact",
        officialSourceUrl: HISTORY_URL,
        confirmed: true,
      },
      {
        id: "history-79-exam",
        examId: "history-advanced",
        type: "exam",
        title: "제79회 시험",
        startAt: "2026-08-09T10:00:00+09:00",
        endAt: "2026-08-09T11:50:00+09:00",
        timePrecision: "exact",
        officialSourceUrl: HISTORY_URL,
        confirmed: true,
      },
      {
        id: "history-79-result",
        examId: "history-advanced",
        type: "result",
        title: "제79회 합격자 발표",
        startAt: "2026-08-21T10:00:00+09:00",
        timePrecision: "date-only",
        officialSourceUrl: HISTORY_URL,
        confirmed: true,
      },
    ],
    preparation: [
      { id: "history-ticket", category: "ticket", label: "수험표", detail: "본인 식별이 가능한 증명사진이 인쇄된 수험표", required: true, officialSourceUrl: HISTORY_GUIDE_URL },
      { id: "history-id", category: "identity", label: "신분증", detail: "공식 응시요강에서 인정하는 신분증", required: true, officialSourceUrl: HISTORY_GUIDE_URL },
      { id: "history-marker", category: "writing", label: "컴퓨터용 수성사인펜", detail: "답안 작성용", required: true, officialSourceUrl: HISTORY_GUIDE_URL },
      { id: "history-tape", category: "writing", label: "수정테이프", detail: "수정액 대신 수정테이프 권장", required: false, officialSourceUrl: HISTORY_GUIDE_URL },
    ],
  },
  {
    id: "computer-specialist-1",
    slug: "computer-specialist-1",
    name: "컴퓨터활용능력 1급",
    shortName: "컴활 1급",
    organizer: "대한상공회의소",
    category: "사무·정보",
    goals: ["취업", "이직", "공무원"],
    description: "스프레드시트와 데이터베이스 활용 역량을 평가하는 상시검정입니다.",
    officialUrl: KORCHAM_URL,
    applicationUrl: KORCHAM_URL,
    scheduleType: "rolling",
    trustLevel: "official-notice",
    lastVerifiedAt: "2026-07-16T00:00:00+09:00",
    timePrecision: "date-only",
    practical: true,
    eligibilityRestricted: false,
    duration: "medium",
    caution: "시험장별 개설 상황이 달라 고정 접수 D-day를 제공하지 않습니다.",
    events: [],
    preparation: genericPreparation(KORCHAM_URL),
  },
  {
    id: "computer-specialist-2",
    slug: "computer-specialist-2",
    name: "컴퓨터활용능력 2급",
    shortName: "컴활 2급",
    organizer: "대한상공회의소",
    category: "사무·정보",
    goals: ["취업", "이직", "자기계발"],
    description: "사무 현장에서 많이 쓰는 스프레드시트 기본 활용 역량을 평가합니다.",
    officialUrl: KORCHAM_URL,
    applicationUrl: KORCHAM_URL,
    scheduleType: "rolling",
    trustLevel: "official-notice",
    lastVerifiedAt: "2026-07-16T00:00:00+09:00",
    timePrecision: "date-only",
    practical: true,
    eligibilityRestricted: false,
    duration: "short",
    caution: "상시검정은 시험장을 먼저 선택하고 가능한 날짜를 확인해야 합니다.",
    events: [],
    preparation: genericPreparation(KORCHAM_URL),
  },
  {
    id: "word-processor",
    slug: "word-processor",
    name: "워드프로세서",
    organizer: "대한상공회의소",
    category: "사무·정보",
    goals: ["취업", "자기계발"],
    description: "문서 작성과 사무 정보 처리 기초를 확인하는 상시검정입니다.",
    officialUrl: KORCHAM_URL,
    applicationUrl: KORCHAM_URL,
    scheduleType: "rolling",
    trustLevel: "official-notice",
    lastVerifiedAt: "2026-07-16T00:00:00+09:00",
    timePrecision: "date-only",
    practical: true,
    eligibilityRestricted: false,
    duration: "short",
    caution: "시험장별 개설일과 실기 프로그램 버전을 공식 접수처에서 확인하세요.",
    events: [],
    preparation: genericPreparation(KORCHAM_URL),
  },
  {
    id: "information-engineer",
    slug: "information-engineer",
    name: "정보처리기사",
    organizer: "한국산업인력공단",
    category: "IT·데이터",
    goals: ["취업", "이직", "경력활용"],
    description: "소프트웨어 설계·개발·데이터베이스·정보시스템 역량을 다루는 국가기술자격입니다.",
    officialUrl: QNET_URL,
    applicationUrl: QNET_URL,
    scheduleType: "round",
    trustLevel: "official-api",
    lastVerifiedAt: "2026-07-16T00:00:00+09:00",
    timePrecision: "conventional",
    practical: true,
    eligibilityRestricted: true,
    duration: "long",
    caution: "응시자격과 최신 회차는 Q-Net에서 반드시 확인하세요.",
    events: [],
    preparation: genericPreparation(QNET_URL),
  },
  {
    id: "industrial-safety-engineer",
    slug: "industrial-safety-engineer",
    name: "산업안전기사",
    organizer: "한국산업인력공단",
    category: "안전·기술",
    goals: ["취업", "이직", "경력활용"],
    description: "산업 현장의 안전관리와 위험 예방 전문성을 평가하는 국가기술자격입니다.",
    officialUrl: QNET_URL,
    applicationUrl: QNET_URL,
    scheduleType: "round",
    trustLevel: "official-api",
    lastVerifiedAt: "2026-07-16T00:00:00+09:00",
    timePrecision: "conventional",
    practical: true,
    eligibilityRestricted: true,
    duration: "long",
    caution: "응시자격 제한과 실기 방식은 종목 상세에서 확인하세요.",
    events: [],
    preparation: genericPreparation(QNET_URL),
  },
  {
    id: "electric-engineer",
    slug: "electric-engineer",
    name: "전기기사",
    organizer: "한국산업인력공단",
    category: "전기·기술",
    goals: ["취업", "이직", "경력활용"],
    description: "전기 설비의 설계·운용·안전관리 능력을 평가하는 국가기술자격입니다.",
    officialUrl: QNET_URL,
    applicationUrl: QNET_URL,
    scheduleType: "round",
    trustLevel: "official-api",
    lastVerifiedAt: "2026-07-16T00:00:00+09:00",
    timePrecision: "conventional",
    practical: true,
    eligibilityRestricted: true,
    duration: "long",
    caution: "응시자격과 계산기 허용 기준은 최신 공식 공고를 확인하세요.",
    events: [],
    preparation: genericPreparation(QNET_URL),
  },
  {
    id: "real-estate-agent",
    slug: "real-estate-agent",
    name: "공인중개사",
    organizer: "한국산업인력공단",
    category: "부동산·법률",
    goals: ["재취업", "창업", "자기계발"],
    description: "부동산 중개 실무와 관련 법령 지식을 평가하는 국가전문자격입니다.",
    officialUrl: QNET_URL,
    applicationUrl: QNET_URL,
    scheduleType: "round",
    trustLevel: "official-api",
    lastVerifiedAt: "2026-07-16T00:00:00+09:00",
    timePrecision: "conventional",
    practical: false,
    eligibilityRestricted: false,
    duration: "long",
    caution: "전문자격 접수 시작은 통상 09시지만 해당 회차 공고가 최종 기준입니다.",
    events: [],
    preparation: genericPreparation(QNET_URL),
  },
  {
    id: "social-worker-1",
    slug: "social-worker-1",
    name: "사회복지사 1급",
    organizer: "한국산업인력공단",
    category: "복지·보건",
    goals: ["취업", "재취업", "경력활용"],
    description: "사회복지 실천·정책·조사론 역량을 평가하는 국가전문자격입니다.",
    officialUrl: QNET_URL,
    applicationUrl: QNET_URL,
    scheduleType: "round",
    trustLevel: "official-api",
    lastVerifiedAt: "2026-07-16T00:00:00+09:00",
    timePrecision: "conventional",
    practical: false,
    eligibilityRestricted: true,
    duration: "medium",
    caution: "학력·교과목·경력 요건은 공식 응시자격 안내로 확인하세요.",
    events: [],
    preparation: genericPreparation(QNET_URL),
  },
  {
    id: "national-civil-service-9",
    slug: "national-civil-service-9",
    name: "국가직 9급 공개경쟁채용",
    shortName: "국가직 9급",
    organizer: "인사혁신처",
    category: "공무원",
    goals: ["공무원", "취업", "재취업"],
    description: "국가공무원 9급 공개경쟁채용 시험입니다.",
    officialUrl: CIVIL_URL,
    applicationUrl: CIVIL_URL,
    scheduleType: "announcement",
    trustLevel: "manual-review",
    lastVerifiedAt: "2026-07-16T00:00:00+09:00",
    timePrecision: "date-only",
    practical: false,
    eligibilityRestricted: true,
    duration: "long",
    caution: "직렬·지역·가산점·단계별 일정은 해당 연도 공식 공고에서 확인하세요.",
    events: [],
    preparation: genericPreparation(CIVIL_URL),
  },
];

export function getExam(id: string) {
  return exams.find((exam) => exam.id === id);
}

export function eventRelevantUntil(event: Exam["events"][number]) {
  if (event.endAt) return new Date(event.endAt).getTime();
  if (event.timePrecision === "date-only") {
    const date = event.startAt.slice(0, 10);
    return new Date(`${date}T23:59:59+09:00`).getTime();
  }
  return new Date(event.startAt).getTime();
}

export function getUpcomingEvents(now = new Date()) {
  return exams
    .flatMap((exam) => exam.events.map((event) => ({ exam, event })))
    .filter(({ event }) => eventRelevantUntil(event) >= now.getTime())
    .sort((a, b) => {
      const aStart = new Date(a.event.startAt).getTime();
      const bStart = new Date(b.event.startAt).getTime();
      const aActive = aStart <= now.getTime();
      const bActive = bStart <= now.getTime();
      if (aActive !== bActive) return aActive ? -1 : 1;
      return aStart - bStart;
    });
}
